# Generated by Django 4.0.3 on 2022-04-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMundial', '0002_alter_sede_ciudad_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='letra_grupo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='pais_equipo',
            field=models.CharField(max_length=15),
        ),
    ]
